# 灵猫墨韵古典文学数据处理系统配置文件

# 数据路径配置
paths:
  input_dir: "collection"          # 原始数据目录
  output_dir: "dataset"            # 处理后数据输出目录
  temp_dir: "logs/temp"            # 临时文件目录
  log_dir: "logs"                  # 日志目录

# 处理器配置
processor:
  batch_size: 1000                 # 批处理大小
  max_workers: 8                   # 最大工作线程数
  file_extensions: [".json", ".txt", ".jsonl"] # 支持的文件扩展名

# 清洗和过滤规则 (processor.py 使用)
cleaning_rules:
  # 基础清洗
  remove_html: true
  normalize_whitespace: true
  remove_control_chars: true
  normalize_punctuation: true
  remove_urls: true
  remove_emojis: true

  # PII 编辑 (需要安装 presidio 和 spacy 模型)
  redact_pii: false
  pii_spacy_model: "en_core_web_lg" # 用于 Presidio 的 Spacy 模型 (例如 en_core_web_lg, zh_core_web_lg)
  pii_entities: # 要检测和编辑的 PII 实体列表 (Presidio 支持的)
    - PERSON
    - PHONE_NUMBER
    - EMAIL_ADDRESS
    - LOCATION # 可能过于宽泛，根据需要调整
    # - CREDIT_CARD # 取决于数据源
    # - US_SSN
    # 添加更多需要的实体...
  pii_redaction_method: "replace" # 可选: 'replace', 'mask', 'hash', 'remove'
  pii_replacement_tag: "[PII]" # 当 method='replace' 时使用

  # 有害内容过滤 (需要配置模型或 API)
  filter_harmful: false
  harmful_model_path: null # Hugging Face 模型标识符或本地路径 (例如 "bert-base-uncased-toxicity")
  harmful_threshold: 0.7 # 模型预测的置信度阈值
  # harmful_api_key: null # 如果使用第三方 API (例如 Perspective API)

  # 质量过滤
  filter_quality: false
  min_length: 10 # 最小文本长度
  max_length: 10000 # 最大文本长度
  max_symbol_ratio: 0.1 # 最大非字母/数字/空白字符比例

  filter_by_language: false # 是否启用语言过滤
  allowed_languages: ["zh", "en"] # 允许的语言代码 (ISO 639-1)
  lang_detection_method: "langdetect" # 可选: 'langdetect', 'fasttext'
  fasttext_model_path: null # 如果 method='fasttext', 指定模型路径 (例如 lid.176.bin)

  filter_repetition: false # 是否启用重复过滤
  repetition_ngram_size: 5 # 用于检测重复的 n-gram 大小
  repetition_threshold: 0.3 # 重复 n-gram 的最大比例阈值

# 内容生成配置
content_generator:
  # 赏析生成配置
  appreciation:
    enabled: true
    model: "gpt-4"                 # 使用的模型
    temperature: 0.7               # 生成温度
    max_tokens: 1000               # 最大生成令牌数
  
  # 问答生成配置
  qa:
    enabled: true
    types:                         # 问答类型及权重
      translation: 0.3             # 翻译
      appreciation: 0.2            # 赏析
      recitation: 0.1              # 背诵
      introduction: 0.1            # 介绍
      summary: 0.1                 # 总结
      segmentation: 0.05           # 分词
      creative: 0.05               # 创作
      allusion: 0.05               # 典故
      comparison: 0.05             # 比较
    variations_per_type: 3         # 每种类型的变体数量

# 质量控制配置
quality_control:
  machine_evaluation:
    enabled: true
    min_score: 0.7                 # 最低接受分数
  
  ai_evaluation:
    enabled: true
    sample_rate: 0.1               # 抽样率
    model: "gpt-4"
  
  human_review:
    enabled: true
    sample_size: 100               # 人工审核样本大小
    high_risk_threshold: 0.8       # 高风险阈值

# 版本控制配置
version_control:
  track_dependencies: true
  version_format: "v{major}.{minor}.{patch}"
  current_version: "v2.0.0"

# 系统配置
system:
  log_level: "INFO"
  night_mode:                      # 夜间模式配置
    enabled: true
    start_time: "21:00"
    end_time: "08:00"
    resource_limits:
      max_workers: 12              # 夜间模式下最大工作线程数

# 分词器配置
tokenizer:
  vocab_size: 30000                # 词汇表大小
  special_tokens:                  # 特殊符号列表
    - "[UNK]"
    - "[CLS]"
    - "[SEP]"
    - "[PAD]"
    - "[MASK]"
  dictionary_path: "dataset/dictionaries/classical_terms.txt"  # 古文专用词典路径
  evaluation:                      # 评估配置
    sample_types:                  # 评估样本类型
      - "prose"
      - "poem"
      - "article"
      - "chu_ci"
    dynasties:                     # 朝代分类
      - "先秦"
      - "汉"
      - "唐"
      - "宋"
      - "元"
      - "明"
      - "清"
      - "现代"